### PR TITLE
[simd/jit]: Implement simd type conversion instructions

### PR DESCRIPTION
**Pull request by haoyu-zc**
Tested by:
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_int_to_int_extend.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_conversions.bin.wast`

### CODE REVIEW

**Review by titzer — APPROVED** [review]
lgtm

**Comment by titzer** [comment]
Can you resolve the conflicts on this PR?

**Comment by haoyu-zc** [comment]
Sure! Resolved.

**Comment by titzer** [comment]
> Sure! Resolved.

Thanks.

**Pull request merged**
