### PR TITLE
[simd/jit]: Implement v128.load and v128.store

### PR DESCRIPTION
**Pull request by haoyu-zc**
Tested by:
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_store.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load.bin.wast`

### CODE REVIEW

**Comment by haoyu-zc** [comment]
It seems the CI failed because `./update.sh` didn't clone the  spec repo correctly

**Comment by titzer** [comment]
> Yeah I think it's because they just changed from using `ocambuild` to using `dune` for the interpreter build: [WebAssembly/spec@653938a](https://github.com/WebAssembly/spec/commit/653938a88c6f40eb886d5980ca315136eb861d03)

Acknowledged. Wizard's CI scripts will have to be updated.

**Comment by titzer** [comment]
I haven't had a chance to look at this yet. Can you PTAL at ci/*/*.sh and see what steps should be done there instead of the ocamlbuild that it currently does?

**Comment by haoyu-zc** [comment]
Yes just got some free time and I am looking into it.


On Jul 28, 2023, at 16:13, Ben L. Titzer ***@***.***> wrote:



I haven't had a chance to look at this yet. Can you PTAL at ci//.sh and see what steps should be done there instead of the ocamlbuild that it currently does?

**Comment by haoyu-zc** [comment]
Fixed. Tested on my forked repo.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by haoyu-zc** [comment]
Will rebase and then push again for this change

**Review by titzer — APPROVED** [review]
lgtm

**Pull request merged**
