### PR TITLE
Fix failing multi-memory test

### PR DESCRIPTION
**Pull request by ejrgilbert**

### CODE REVIEW

**Comment by ejrgilbert** [comment]
This test should work after PR #226 is merged.

**Comment by ejrgilbert** [comment]
@titzer What would happen if you're needing to use `puts` in a multi-memory context?

**Comment by matthew-mojira** [comment]
What a great PR!

**Comment by titzer** [comment]
> @titzer What would happen if you're needing to use `puts` in a multi-memory context?

`wizeng.puts` tries to bind to the first exported memory of a module. The logic is in `src/modules/wizeng/WizengModule.v3`.

**Pull request merged**
